<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/Site.master" CodeBehind="ViewComplaints_ControlRoom.aspx.cs" Inherits="ExciseAPI.ECMS.ViewComplaints_ControlRoom" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <div class="w-100 fl container-fluid">

        <div class="block black bg-white">
            <div class="head">Complaints</div>
            <div class="content">
                <asp:GridView ID="gvcomplaintdetails" runat="server" ShowFooter="false" AutoGenerateDeleteButton="false" AutoGenerateColumns="false"
                    EmptyDataText="No Data are available to show" EmptyDataRowStyle-HorizontalAlign="Center"
                    ShowHeaderWhenEmpty="True" FooterStyle-BackColor="#ffcc66" 
                    CssClass="table table-striped table-bordered nowrap gvv" OnRowDataBound="gvcomplaintdetails_RowDataBound" OnRowCommand="gvcomplaintdetails_RowCommand">
                     <HeaderStyle BackColor="#8ad77c" />
                    <Columns>
                        <asp:TemplateField HeaderText="SI.No" ItemStyle-CssClass="txt-cnt">
                            <ItemTemplate>
                                <%#Container.DataItemIndex + 1 %>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:BoundField DataField="ComplaintID" HeaderText="Complaint ID" />
                        <asp:BoundField DataField="Name" HeaderText="Name" />
                        <asp:BoundField DataField="Phone" HeaderText="Phone" />
                        <asp:BoundField DataField="DistName" HeaderText="District Name" />
                        <asp:BoundField DataField="MandName" HeaderText="Mandal Name" />
                        <asp:BoundField DataField="VillName" HeaderText="Village Name" />
                        <asp:BoundField DataField="Status" HeaderText="Status" />
                        <asp:BoundField DataField="CreatedDate" HeaderText="Created Date" />
                        <asp:TemplateField HeaderText="View" ItemStyle-CssClass="txt-cnt">
                            <ItemTemplate>
                                <asp:LinkButton ID="lnkview" runat="server" Text="Click..!" CommandName="View" CommandArgument='<%# Eval("ComplaintID").ToString() + "," + Eval("StatusID").ToString() %>' ForeColor="Green"></asp:LinkButton>
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                </asp:GridView>
            </div>
        </div>
    </div>
</asp:Content>

